on:
  pull_request:
    types:
      - opened
jobs:
  run_if:
    if:  startsWith(github.head_ref, 'migration/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "The head of this PR starts with 'migration/'"
