name: Migration run on Churrera
on:
  pull_request:
    types:
      - [opened, synchronize]
jobs:
  run_if:
    if:  startsWith(github.head_ref, 'migration/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test Run script
        run: |
          python3 main.py
      
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: bufbuild/buf-setup-action@v0.1.0
        with:
          version: '0.43.2'
      - name: Generating gRPC files
        run: make generate
      - uses: setare/git-changes-action@v0.1.2
        with:
          github_token: ${{ github.token }}
          name: 'File generation check'