name: Migrations Churrera
on:
  pull_request:
    types: [opened]
jobs:
  job_1:
    run_if:
      if:  startsWith(github.head_ref, 'migration/')
      name: Migrations files
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.7", "3.8", "3.9", "3.10"]

      steps:
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Lint with flake8
          run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        - name: Test Run script
          run: |
            python3 main.py
        - run: pwd
        - run: ls -la
        - name: Upload result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          # path: math-homework.txt
  job_2:
    name: Committed results
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: pwd
      - run: ls -la
      - name: Download result for job 1
        uses: actions/download-artifact@v3
        with:
          name: homework
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Darian Campos
          author_email: darian.campos@pedidosya.com
          message: 'Migration success'
          add: '*.txt --force'
          # cwd: './migration/'